const colors = {
  light: {
    text: "#0a0a0a",
    tint: "#FF6B35",
    background: "#F7F8FC",
    foreground: "#0F1117",
    card: "#FFFFFF",
    cardForeground: "#0F1117",
    primary: "#FF6B35",
    primaryForeground: "#FFFFFF",
    secondary: "#FFF0EA",
    secondaryForeground: "#CC3D00",
    muted: "#F0F2F7",
    mutedForeground: "#6B7280",
    accent: "#FFF0EA",
    accentForeground: "#CC3D00",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    success: "#22C55E",
    successForeground: "#FFFFFF",
    warning: "#F59E0B",
    warningForeground: "#FFFFFF",
    border: "#E5E8EF",
    input: "#E5E8EF",
    surface: "#F0F2F7",
  },
  dark: {
    text: "#FFFFFF",
    tint: "#FF6B35",
    background: "#0F1117",
    foreground: "#FFFFFF",
    card: "#1A1D27",
    cardForeground: "#FFFFFF",
    primary: "#FF6B35",
    primaryForeground: "#FFFFFF",
    secondary: "#2D1810",
    secondaryForeground: "#FF9970",
    muted: "#252836",
    mutedForeground: "#8B8FA8",
    accent: "#2D1810",
    accentForeground: "#FF9970",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    success: "#22C55E",
    successForeground: "#FFFFFF",
    warning: "#F59E0B",
    warningForeground: "#FFFFFF",
    border: "#2A2D3A",
    input: "#252836",
    surface: "#252836",
  },
  radius: 14,
};

export default colors;
